name: First workflow
on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a welcome message
        run: echo "Welcome to github actins workflow"
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      - name: List Repo files
        run: ls -la
    
  
